FROM maven:3.9 AS build

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV CATALINA_OPTS="-Duser.timezone=UTC"

COPY ./pom.xml /userService/pom.xml
WORKDIR /userService
RUN mvn dependency:go-offline
COPY ./src/ /userService/src
WORKDIR /userService
RUN mvn clean install -DskipTests

FROM eclipse-temurin:25-jdk
WORKDIR /userService
COPY --from=build /userService/target/userService-0.0.1-SNAPSHOT.jar /userService/userService.jar
EXPOSE 8080
CMD ["java", "-jar", "userService.jar"]
